<?php
include("pear/Calculator.class.php"); 
/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-06-28 at 15:46:34.
 */
class CalculatorTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Calculator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Calculator;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function provider()
    {
        return array(
          array(0, 0, 0),
          array(0, 1, 1),
          array(1, 0, 1),
          array(1, 1, 2),
        );
    }

    /**
     * Generated from @assert (0, 0) == 0.
     *
     * @covers Calculator::add
     * 
     * @dataProvider provider 
     */
    public function testAdd($a, $b, $c)
    {
        $this->assertEquals(
          $c,
          $this->object->add($a, $b)
        );
    }
}
